// src/lib/components/CookieConsent.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { type CookiePreferences, getGdprPreferences, saveGdprPreferences } from '$lib/cookies';
	import { optInAnalytics, optOutAnalytics, isPostHogLoaded, getPostHog } from '$lib/posthog';

	/**
	 * Optional callbacks when preferences change.
	 * Used by main site for feature flags.
	 */
	interface Props {
		onAnalyticsChange?: (enabled: boolean) => void;
	}

	let { onAnalyticsChange }: Props = $props();

	let preferences: CookiePreferences = $state({
		necessary: true,
		analytics: false,
		marketing: false
	});

	let showBanner = $state(false);
	let showSettings = $state(false);
	let mounted = $state(false);
	let hasConsented = $state(false);

	onMount(() => {
		mounted = true;
		const saved = getGdprPreferences();
		if (saved) {
			preferences = { ...preferences, ...saved };
			hasConsented = true;
			applyPreferences();
		} else {
			showBanner = true;
		}
	});

	function applyPreferences() {
		if (isPostHogLoaded()) {
			if (preferences.analytics) {
				optInAnalytics();
				getPostHog()?.reloadFeatureFlags();
			} else {
				optOutAnalytics();
			}
		}
		onAnalyticsChange?.(preferences.analytics);
	}

	function savePreferences() {
		saveGdprPreferences(preferences);
		hasConsented = true;
		showBanner = false;
		showSettings = false;
		applyPreferences();
	}

	function acceptAll() {
		preferences = { necessary: true, analytics: true, marketing: true };
		savePreferences();
	}

	function rejectAll() {
		preferences = { necessary: true, analytics: false, marketing: false };
		savePreferences();
	}

	function openSettings() {
		showSettings = true;
		showBanner = true;
	}

	function closeSettings() {
		showSettings = false;
		if (hasConsented) {
			showBanner = false;
		}
	}
</script>

{#if mounted}
	{#if showBanner && !showSettings}
		<div class="spacer"></div>
	{/if}
	{#if showBanner}
		<div class="overlay" class:visible={showSettings}></div>
		<div class="banner" class:settings-open={showSettings}>
			{#if showSettings}
				<div class="settings-panel">
					<div class="settings-header">
						<h3 class="title">Cookie Preferences</h3>
						<button class="close-btn" onclick={closeSettings} aria-label="Close">
							<svg
								xmlns="http://www.w3.org/2000/svg"
								width="20"
								height="20"
								viewBox="0 0 24 24"
								fill="none"
								stroke="currentColor"
								stroke-width="2"
								stroke-linecap="round"
								stroke-linejoin="round"
							>
								<line x1="18" y1="6" x2="6" y2="18"></line>
								<line x1="6" y1="6" x2="18" y2="18"></line>
							</svg>
						</button>
					</div>
					<p class="settings-description">
						Manage your cookie preferences below. You can enable or disable different types of
						cookies. See our <a href="/privacy">privacy policy</a> for more details.
					</p>

					<div class="cookie-options">
						<div class="cookie-option">
							<div class="option-header">
								<label class="option-label">
									<input type="checkbox" checked disabled />
									<span class="checkbox disabled"></span>
									<span class="option-title">Necessary</span>
								</label>
								<span class="always-on">Always on</span>
							</div>
							<p class="option-description">
								Essential cookies required for the website to function. These cannot be disabled.
							</p>
						</div>

						<div class="cookie-option">
							<div class="option-header">
								<label class="option-label">
									<input type="checkbox" bind:checked={preferences.analytics} />
									<span class="checkbox"></span>
									<span class="option-title">Analytics</span>
								</label>
							</div>
							<p class="option-description">
								Help us understand how visitors interact with our website by collecting anonymous
								usage data.
							</p>
						</div>
					</div>

					<div class="settings-buttons">
						<button class="btn btn-secondary" onclick={rejectAll}>Reject All</button>
						<button class="btn btn-secondary" onclick={acceptAll}>Accept All</button>
						<button class="btn btn-primary" onclick={savePreferences}>Save Preferences</button>
					</div>
				</div>
			{:else}
				<div class="content">
					<div class="text-content">
						<h3 class="title">Cookie Settings</h3>
						<p class="description">
							We use cookies to improve your experience and analyze site traffic. See our <a
								href="/privacy">privacy policy</a
							> for details.
						</p>
					</div>
					<div class="buttons">
						<button class="btn btn-link" onclick={openSettings}>Customize</button>
						<button class="btn btn-secondary" onclick={rejectAll}>Reject All</button>
						<button class="btn btn-primary" onclick={acceptAll}>Accept All</button>
					</div>
				</div>
			{/if}
		</div>
	{:else if hasConsented}
		<button class="toggle" onclick={openSettings} aria-label="Cookie settings">
			<svg
				xmlns="http://www.w3.org/2000/svg"
				width="20"
				height="20"
				viewBox="0 0 24 24"
				fill="none"
				stroke="currentColor"
				stroke-width="2"
				stroke-linecap="round"
				stroke-linejoin="round"
			>
				<circle cx="12" cy="12" r="10" />
				<circle cx="8" cy="9" r="1.5" fill="currentColor" />
				<circle cx="15" cy="8" r="1.5" fill="currentColor" />
				<circle cx="10" cy="14" r="1.5" fill="currentColor" />
				<circle cx="16" cy="13" r="1.5" fill="currentColor" />
				<circle cx="13" cy="17" r="1" fill="currentColor" />
			</svg>
		</button>
	{/if}
{/if}

<style>
	.spacer {
		height: 120px;
	}

	@media (min-width: 768px) {
		.spacer {
			height: 72px;
		}
	}

	.overlay {
		position: fixed;
		inset: 0;
		background: rgba(0, 0, 0, 0);
		z-index: 9998;
		pointer-events: none;
		transition: background 200ms;
	}

	.overlay.visible {
		background: rgba(0, 0, 0, 0.5);
		pointer-events: auto;
	}

	.banner {
		position: fixed;
		bottom: 0;
		left: 0;
		right: 0;
		background: rgb(var(--c-gray-800));
		border-top: 1px solid rgb(var(--c-gray-700));
		padding: 1.25rem;
		z-index: 9999;
	}

	.banner.settings-open {
		bottom: auto;
		top: 50%;
		left: 50%;
		right: auto;
		transform: translate(-50%, -50%);
		max-width: 500px;
		width: calc(100% - 2rem);
		border: 1px solid rgb(var(--c-gray-700));
		border-radius: 0.5rem;
		max-height: 90vh;
		overflow-y: auto;
	}

	.content {
		max-width: 1200px;
		margin: 0 auto;
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	.text-content {
		flex: 1;
	}

	@media (min-width: 768px) {
		.content {
			flex-direction: row;
			align-items: center;
			justify-content: space-between;
		}
	}

	.title {
		color: rgb(var(--c-white));
		font-size: 1rem;
		font-weight: 600;
		margin: 0 0 0.25rem 0;
	}

	.description {
		color: rgb(var(--c-gray-400));
		font-size: 0.875rem;
		margin: 0;
	}

	.description a,
	.settings-description a {
		color: rgb(var(--c-blue-400));
		text-decoration: underline;
	}

	.description a:hover,
	.settings-description a:hover {
		color: rgb(var(--c-blue-300));
	}

	.buttons {
		display: flex;
		gap: 0.5rem;
		flex-shrink: 0;
		flex-wrap: wrap;
	}

	.btn {
		padding: 0.5rem 1rem;
		border-radius: 0.375rem;
		font-weight: 500;
		font-size: 0.875rem;
		cursor: pointer;
		transition:
			background-color 150ms,
			border-color 150ms,
			color 150ms;
	}

	.btn-primary {
		background: #1d4ed8;
		color: #ffffff;
		border: 1px solid #2563eb;
	}

	.btn-primary:hover {
		background: #2563eb;
		border-color: rgb(var(--c-blue-500));
	}

	.btn-secondary {
		background: transparent;
		color: rgb(var(--c-gray-400));
		border: 1px solid rgb(var(--c-gray-700));
	}

	.btn-secondary:hover {
		background: rgb(var(--c-gray-700));
		border-color: rgb(var(--c-gray-600));
		color: rgb(var(--c-gray-200));
	}

	.btn-link {
		background: transparent;
		color: rgb(var(--c-gray-400));
		border: 1px solid transparent;
		text-decoration: underline;
	}

	.btn-link:hover {
		color: rgb(var(--c-gray-200));
	}

	/* Settings panel styles */
	.settings-panel {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	.settings-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
	}

	.close-btn {
		background: transparent;
		border: none;
		color: rgb(var(--c-gray-400));
		cursor: pointer;
		padding: 0.25rem;
		display: flex;
		align-items: center;
		justify-content: center;
		border-radius: 0.25rem;
	}

	.close-btn:hover {
		color: rgb(var(--c-white));
		background: rgb(var(--c-gray-700));
	}

	.settings-description {
		color: rgb(var(--c-gray-400));
		font-size: 0.875rem;
		margin: 0;
	}

	.cookie-options {
		display: flex;
		flex-direction: column;
		gap: 1rem;
		margin: 0.5rem 0;
	}

	.cookie-option {
		background: rgb(var(--c-gray-900));
		border: 1px solid rgb(var(--c-gray-700));
		border-radius: 0.375rem;
		padding: 1rem;
	}

	.option-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		margin-bottom: 0.5rem;
	}

	.option-label {
		display: flex;
		align-items: center;
		gap: 0.75rem;
		cursor: pointer;
	}

	.option-label input {
		position: absolute;
		opacity: 0;
		pointer-events: none;
	}

	.checkbox {
		width: 1.25rem;
		height: 1.25rem;
		border: 1px solid rgb(var(--c-gray-600));
		border-radius: 0.25rem;
		background: rgb(var(--c-gray-700));
		display: flex;
		align-items: center;
		justify-content: center;
		flex-shrink: 0;
		transition:
			background 150ms,
			border-color 150ms;
	}

	.checkbox.disabled {
		opacity: 0.6;
		cursor: not-allowed;
	}

	.option-label input:checked + .checkbox {
		background: #2563eb;
		border-color: #2563eb;
	}

	.option-label input:checked + .checkbox::after {
		content: '';
		width: 0.5rem;
		height: 0.75rem;
		border: solid white;
		border-width: 0 2px 2px 0;
		transform: rotate(45deg) translateY(-1px);
	}

	.option-label:hover .checkbox:not(.disabled) {
		border-color: rgb(var(--c-gray-500));
	}

	.option-title {
		color: rgb(var(--c-white));
		font-weight: 500;
		font-size: 0.9375rem;
	}

	.always-on {
		color: rgb(var(--c-gray-500));
		font-size: 0.75rem;
		text-transform: uppercase;
		letter-spacing: 0.05em;
	}

	.option-description {
		color: rgb(var(--c-gray-400));
		font-size: 0.8125rem;
		margin: 0;
		line-height: 1.4;
	}

	.settings-buttons {
		display: flex;
		gap: 0.5rem;
		justify-content: flex-end;
		flex-wrap: wrap;
		padding-top: 0.5rem;
		border-top: 1px solid rgb(var(--c-gray-700));
	}

	/* Toggle button */
	.toggle {
		position: fixed;
		bottom: 1rem;
		right: 1rem;
		width: 3rem;
		height: 3rem;
		border-radius: 50%;
		background: rgb(var(--c-gray-800));
		border: 1px solid rgb(var(--c-gray-700));
		color: rgb(var(--c-gray-400));
		cursor: pointer;
		display: flex;
		align-items: center;
		justify-content: center;
		box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.3);
		z-index: 9999;
		transition:
			background-color 150ms,
			color 150ms;
	}

	.toggle:hover {
		background: rgb(var(--c-gray-700));
		color: rgb(var(--c-white));
	}
</style>

// docs/src/components/CookieConsent.tsx
'use client';

import { useState, useEffect } from 'react';
import {
  type CookiePreferences,
  getGdprPreferences,
  saveGdprPreferences,
} from '$lib/cookies';
import {
  optInAnalytics,
  optOutAnalytics,
  isPostHogLoaded,
  getPostHog,
} from '$lib/posthog';

export function CookieConsent() {
  const [preferences, setPreferences] = useState<CookiePreferences>({
    necessary: true,
    analytics: false,
    marketing: false,
  });
  const [showBanner, setShowBanner] = useState(false);
  const [showSettings, setShowSettings] = useState(false);
  const [mounted, setMounted] = useState(false);
  const [hasConsented, setHasConsented] = useState(false);

  useEffect(() => {
    setMounted(true);
    const saved = getGdprPreferences();
    if (saved) {
      setPreferences({ ...preferences, ...saved });
      setHasConsented(true);
      applyPreferences(saved);
    } else {
      setShowBanner(true);
    }
  }, []);

  function applyPreferences(prefs: CookiePreferences) {
    if (isPostHogLoaded()) {
      if (prefs.analytics) {
        optInAnalytics();
        getPostHog()?.reloadFeatureFlags();
      } else {
        optOutAnalytics();
      }
    }
  }

  function savePrefs() {
    saveGdprPreferences(preferences);
    setHasConsented(true);
    setShowBanner(false);
    setShowSettings(false);
    applyPreferences(preferences);
  }

  function acceptAll() {
    const prefs = { necessary: true, analytics: true, marketing: true };
    setPreferences(prefs);
    saveGdprPreferences(prefs);
    setHasConsented(true);
    setShowBanner(false);
    setShowSettings(false);
    applyPreferences(prefs);
  }

  function rejectAll() {
    const prefs = { necessary: true, analytics: false, marketing: false };
    setPreferences(prefs);
    saveGdprPreferences(prefs);
    setHasConsented(true);
    setShowBanner(false);
    setShowSettings(false);
    applyPreferences(prefs);
  }

  function openSettings() {
    setShowSettings(true);
    setShowBanner(true);
  }

  function closeSettings() {
    setShowSettings(false);
    if (hasConsented) {
      setShowBanner(false);
    }
  }

  if (!mounted) return null;

  return (
    <>
      {showBanner && !showSettings && <div className="h-[100px] md:h-[72px]" />}

      {showBanner && (
        <>
          <div
            className={`fixed inset-0 z-[9998] pointer-events-none transition-colors duration-200 ${
              showSettings ? 'bg-black/50 pointer-events-auto' : 'bg-transparent'
            }`}
          />

          <div
            className={`fixed z-[9999] bg-[var(--color-fd-card)] border-[var(--color-fd-border)] p-5 ${
              showSettings
                ? 'top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 max-w-[500px] w-[calc(100%-2rem)] border rounded-lg max-h-[90vh] overflow-y-auto'
                : 'bottom-0 left-0 right-0 border-t'
            }`}
          >
            {showSettings ? (
              <div className="flex flex-col gap-4">
                <div className="flex justify-between items-center">
                  <h3 className="text-[var(--color-fd-foreground)] text-base font-semibold m-0">
                    Cookie Preferences
                  </h3>
                  <button
                    onClick={closeSettings}
                    className="bg-transparent border-none text-[var(--color-fd-muted-foreground)] cursor-pointer p-1 flex items-center justify-center rounded hover:text-[var(--color-fd-foreground)] hover:bg-[var(--color-fd-muted)]"
                    aria-label="Close"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="20"
                      height="20"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <line x1="18" y1="6" x2="6" y2="18" />
                      <line x1="6" y1="6" x2="18" y2="18" />
                    </svg>
                  </button>
                </div>

                <p className="text-[var(--color-fd-muted-foreground)] text-sm m-0">
                  Manage your cookie preferences below. You can enable or disable
                  different types of cookies. See our{' '}
                  <a href="/privacy" className="text-[var(--color-fd-primary)] underline hover:text-[var(--color-fd-primary)]">
                    privacy policy
                  </a>{' '}
                  for more details.
                </p>

                <div className="flex flex-col gap-4 my-2">
                  <div className="bg-[var(--color-fd-muted)] border border-[var(--color-fd-border)] rounded-md p-4">
                    <div className="flex justify-between items-center mb-2">
                      <label className="flex items-center gap-3 cursor-pointer">
                        <input
                          type="checkbox"
                          checked
                          disabled
                          className="sr-only"
                        />
                        <span className="w-5 h-5 border border-[#4b5563] rounded bg-[#374151] flex items-center justify-center opacity-60 relative after:content-[''] after:w-2 after:h-3 after:border-white after:border-r-2 after:border-b-2 after:rotate-45 after:-translate-y-0.5" />
                        <span className="text-[var(--color-fd-foreground)] font-medium text-[0.9375rem]">
                          Necessary
                        </span>
                      </label>
                      <span className="text-[var(--color-fd-muted-foreground)] text-xs uppercase tracking-wider">
                        Always on
                      </span>
                    </div>
                    <p className="text-[var(--color-fd-muted-foreground)] text-[0.8125rem] m-0 leading-relaxed">
                      Essential cookies required for the website to function.
                      These cannot be disabled.
                    </p>
                  </div>

                  <div className="bg-[var(--color-fd-muted)] border border-[var(--color-fd-border)] rounded-md p-4">
                    <div className="flex justify-between items-center mb-2">
                      <label className="flex items-center gap-3 cursor-pointer">
                        <input
                          type="checkbox"
                          checked={preferences.analytics}
                          onChange={(e) =>
                            setPreferences({
                              ...preferences,
                              analytics: e.target.checked,
                            })
                          }
                          className="sr-only"
                        />
                        <span
                          className={`w-5 h-5 border rounded flex items-center justify-center transition-colors ${
                            preferences.analytics
                              ? 'bg-blue-600 border-blue-600'
                              : 'border-[#4b5563] bg-[#374151] hover:border-[var(--color-fd-muted-foreground)]'
                          }`}
                        >
                          {preferences.analytics && (
                            <span className="w-2 h-3 border-white border-r-2 border-b-2 rotate-45 -translate-y-0.5" />
                          )}
                        </span>
                        <span className="text-[var(--color-fd-foreground)] font-medium text-[0.9375rem]">
                          Analytics
                        </span>
                      </label>
                    </div>
                    <p className="text-[var(--color-fd-muted-foreground)] text-[0.8125rem] m-0 leading-relaxed">
                      Help us understand how visitors interact with our website
                      by collecting anonymous usage data.
                    </p>
                  </div>
                </div>

                <div className="flex gap-2 justify-end flex-wrap pt-2 border-t border-[var(--color-fd-border)]">
                  <button
                    onClick={rejectAll}
                    className="px-4 py-2 rounded-md font-medium text-sm cursor-pointer transition-colors bg-transparent text-[var(--color-fd-muted-foreground)] border border-[var(--color-fd-border)] hover:bg-[var(--color-fd-muted)] hover:border-[var(--color-fd-border)] hover:text-[var(--color-fd-foreground)]"
                  >
                    Reject All
                  </button>
                  <button
                    onClick={acceptAll}
                    className="px-4 py-2 rounded-md font-medium text-sm cursor-pointer transition-colors bg-transparent text-[var(--color-fd-muted-foreground)] border border-[var(--color-fd-border)] hover:bg-[var(--color-fd-muted)] hover:border-[var(--color-fd-border)] hover:text-[var(--color-fd-foreground)]"
                  >
                    Accept All
                  </button>
                  <button
                    onClick={savePrefs}
                    className="px-4 py-2 rounded-md font-medium text-sm cursor-pointer transition-colors bg-blue-700 text-white border border-blue-600 hover:bg-blue-600 hover:border-blue-500"
                  >
                    Save Preferences
                  </button>
                </div>
              </div>
            ) : (
              <div className="max-w-[1200px] mx-auto flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
                <div className="flex-1">
                  <h3 className="text-[var(--color-fd-foreground)] text-base font-semibold m-0 mb-1">
                    Cookie Settings
                  </h3>
                  <p className="text-[var(--color-fd-muted-foreground)] text-sm m-0">
                    We use cookies to improve your experience and analyze site
                    traffic. See our{' '}
                    <a
                      href="/privacy"
                      className="text-[var(--color-fd-primary)] underline hover:text-[var(--color-fd-primary)]"
                    >
                      privacy policy
                    </a>{' '}
                    for details.
                  </p>
                </div>
                <div className="flex gap-2 flex-shrink-0 flex-wrap">
                  <button
                    onClick={openSettings}
                    className="px-4 py-2 rounded-md font-medium text-sm cursor-pointer transition-colors bg-transparent text-[var(--color-fd-muted-foreground)] border border-transparent underline hover:text-[var(--color-fd-foreground)]"
                  >
                    Customize
                  </button>
                  <button
                    onClick={rejectAll}
                    className="px-4 py-2 rounded-md font-medium text-sm cursor-pointer transition-colors bg-transparent text-[var(--color-fd-muted-foreground)] border border-[var(--color-fd-border)] hover:bg-[var(--color-fd-muted)] hover:border-[var(--color-fd-border)] hover:text-[var(--color-fd-foreground)]"
                  >
                    Reject All
                  </button>
                  <button
                    onClick={acceptAll}
                    className="px-4 py-2 rounded-md font-medium text-sm cursor-pointer transition-colors bg-blue-700 text-white border border-blue-600 hover:bg-blue-600 hover:border-blue-500"
                  >
                    Accept All
                  </button>
                </div>
              </div>
            )}
          </div>
        </>
      )}

      {!showBanner && hasConsented && (
        <button
          onClick={openSettings}
          className="fixed bottom-4 right-4 w-12 h-12 rounded-full bg-[var(--color-fd-card)] border border-[var(--color-fd-border)] text-[var(--color-fd-muted-foreground)] cursor-pointer flex items-center justify-center shadow-lg z-[9999] transition-colors hover:bg-[var(--color-fd-muted)] hover:text-[var(--color-fd-foreground)]"
          aria-label="Cookie settings"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="20"
            height="20"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <circle cx="12" cy="12" r="10" />
            <circle cx="8" cy="9" r="1.5" fill="currentColor" />
            <circle cx="15" cy="8" r="1.5" fill="currentColor" />
            <circle cx="10" cy="14" r="1.5" fill="currentColor" />
            <circle cx="16" cy="13" r="1.5" fill="currentColor" />
            <circle cx="13" cy="17" r="1" fill="currentColor" />
          </svg>
        </button>
      )}
    </>
  );
}
